version: '3'
services:
    nginx:
        build:
            context: ./
            dockerfile: nginx.docker.prod
        image: malkinfedor/cloud-downloader
        volumes:
            - ./frontend:/var/www/html
            - ./test:/var/www/html/test
            - ./backend:/var/www/backend
            - ./downloads:/var/www/downloads
        ports:
            - "8080:80"
        working_dir: /var/www/html

    nginx-test:
        build:
            context: ./test
            dockerfile: nginx.docker
        volumes:
            - ./test:/var/www/html/
            # - ./downloads:/var/www/backend
        ports:
            - "8081:80"
        working_dir: /var/www/html

    develop-php-cli:
        #image: php:7.1-cli
        build:
            context: ./test/docker
            dockerfile: php-cli.docker
        volumes:
            - ./test:/var/www/test
        working_dir: /var/www/test
        tty: true
