version: '3'
services:
    nginx:
        build:
            context: ./frontend/docker
            dockerfile: nginx.docker
        volumes:
            - ./frontend:/var/www/html
            - ./test:/var/www/html/test
        ports:
            - "8080:80"
        working_dir: /var/www/html

    nginx-test:
        build:
            context: ./frontend/docker
            dockerfile: nginx.docker
        volumes:
            - ./test:/var/www/html/
        ports:
            - "8081:80"
        working_dir: /var/www/html

    develop-php-cli:
        #image: php:7.1-cli
        build:
            context: ./test/docker
            dockerfile: php-cli.docker
        volumes:
            - ./test:/var/www/test
        working_dir: /var/www/test
        tty: true